export const resdata = [
  {
    id: 1,
    name: "The Rusty Spoon",
    type: "American",
    rating: 2,
    address: "123 Main St, Cityville",
    phone: "+1 (555) 123-4567",
    image: "https://example.com/images/rusty_spoon.jpg",
    menu: [
      { item: "Burger", price: 10.99 },
      { item: "Steak", price: 20.99 },
      { item: "Salad", price: 8.99 },
    ],
  },
  {
    id: 2,
    name: "La Trattoria",
    type: "Italian",
    rating: 3,
    address: "456 Oak St, Townsville",
    phone: "+1 (555) 987-6543",
    image: "https://example.com/images/la_trattoria.jpg",
    menu: [
      { item: "Pizza Margherita", price: 12.99 },
      { item: "Pasta Carbonara", price: 15.99 },
      { item: "Tiramisu", price: 7.99 },
    ],
  },
  {
    id: 3,
    name: "Golden Dragon",
    type: "Chinese",
    rating: 4,
    address: "789 Maple Ave, Chinatown",
    phone: "+1 (555) 234-5678",
    image: "https://example.com/images/golden_dragon.jpg",
    menu: [
      { item: "Kung Pao Chicken", price: 9.99 },
      { item: "Beef with Broccoli", price: 11.99 },
      { item: "Spring Rolls", price: 6.99 },
    ],
  },
  {
    id: 4,
    name: "Sushi Samba",
    type: "Japanese",
    rating: 4.1,
    address: "321 Cherry St, Little Tokyo",
    phone: "+1 (555) 345-6789",
    image: "https://example.com/images/sushi_samba.jpg",
    menu: [
      { item: "Sashimi Platter", price: 22.99 },
      { item: "California Roll", price: 14.99 },
      { item: "Miso Soup", price: 4.99 },
    ],
  },
  {
    id: 5,
    name: "Mamma Mia Pizzeria",
    type: "Italian",
    rating: 5,
    address: "987 Elm St, Little Italy",
    phone: "+1 (555) 456-7890",
    image: "https://example.com/images/mamma_mia_pizzeria.jpg",
    menu: [
      { item: "Margherita Pizza", price: 16.99 },
      { item: "Spaghetti Bolognese", price: 13.99 },
      { item: "Gelato", price: 5.99 },
    ],
  },
  {
    id: 6,
    name: "The French Quarter",
    type: "French",
    rating: 4.5,
    address: "741 Bourbon St, New Orleans",
    phone: "+1 (555) 567-8901",
    image: "https://example.com/images/french_quarter.jpg",
    menu: [
      { item: "Croque Monsieur", price: 11.99 },
      { item: "Coq au Vin", price: 18.99 },
      { item: "Crème Brûlée", price: 8.99 },
    ],
  },
  {
    id: 7,
    name: "Tandoori Palace",
    type: "Indian",
    rating: 3.7,
    address: "852 Spice St, Mumbai",
    phone: "+1 (555) 678-9012",
    image: "https://example.com/images/tandoori_palace.jpg",
    menu: [
      { item: "Chicken Tikka Masala", price: 12.99 },
      { item: "Vegetable Biryani", price: 14.99 },
      { item: "Naan Bread", price: 3.99 },
    ],
  },
  {
    id: 8,
    name: "El Mariachi",
    type: "Mexican",
    rating: 4.2,
    address: "963 Guacamole Ave, Cancun",
    phone: "+1 (555) 789-0123",
    image: "https://example.com/images/el_mariachi.jpg",
    menu: [
      { item: "Tacos al Pastor", price: 9.99 },
      { item: "Enchiladas Verdes", price: 13.99 },
      { item: "Margarita", price: 7.99 },
    ],
  },
  {
    id: 9,
    name: "The Greek Taverna",
    type: "Greek",
    rating: 2.5,
    address: "654 Olive St, Athens",
    phone: "+1 (555) 890-1234",
    image: "https://example.com/images/greek_taverna.jpg",
    menu: [
      { item: "Gyro Platter", price: 14.99 },
      { item: "Moussaka", price: 16.99 },
      { item: "Baklava", price: 6.99 },
    ],
  },
  {
    id: 10,
    name: "Ramen House",
    type: "Japanese",
    rating: 4.6,
    address: "246 Noodle Blvd, Tokyo",
    phone: "+1 (555) 012-3456",
    image: "https://example.com/images/ramen_house.jpg",
    menu: [
      { item: "Tonkotsu Ramen", price: 11.99 },
      { item: "Shoyu Ramen", price: 12.99 },
      { item: "Edamame", price: 4.99 },
    ],
  },
  {
    id: 11,
    name: "Café Parisien",
    type: "French",
    address: "357 Eiffel Tower St, Paris",
    phone: "+1 (555) 234-5678",
    image: "https://example.com/images/cafe_parisien.jpg",
    menu: [
      { item: "Croissant", price: 3.99 },
      { item: "Quiche Lorraine", price: 9.99 },
      { item: "Macarons", price: 7.99 },
    ],
  },
];
